build:
  maxIssues: 0

config:
  validation: true

complexity:
  LongMethod:
    active: true
    threshold: 40
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 7

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
  MaxLineLength:
    active: false
